### ISSUE TITLE
HiDPI 設置?

### ISSUE THREAD

**Issue by nemolus** [countstarlight/deepin-wine-tim-arch#1]
請問可以支持 HiDPI 嗎? 如果可以的話, 應該如何設置呢?

在 2k/4k 屏幕下字體和圖標等都非常小.

我嘗試 Arch Wiki 的辦法但沒有用:
https://wiki.archlinux.org/index.php/HiDPI#Wine_applications

謝謝!

**Comment by countstarlight** [comment]
经过搜索与尝试发现，可以修改`winecfg`中的dpi设置
```shell
env WINEPREFIX="$HOME/.deepinwine/Deepin-TIM" winecfg
```
`$HOME`为你的用户目录，如`/home/countstarlight`
在`Graphics`选项卡中修改dpi，如 修改为210，这样应该能解决

**Comment by nemolus** [comment]
經測試可用, 非常感謝!

**Comment by tcstory** [comment]
ubuntu 18.04 会报错,这是系统的原因吗?

```
$ env WINEPREFIX="$HOME/.deepinwine/Deepin-TIM" winecfg
env: ‘winecfg’: No such file or directory


```

**Comment by countstarlight** [comment]
@tcstory 这个库适用Archlinux和它的衍生发行版，你是如何在ubuntu上安装的？

**Comment by tcstory** [comment]
@countstarlight 哦,我没有说清楚,其实我只是在别的地方安装了deepin-tim, 不是直接安装你的包,然后也遇到了同样的问题, 后面我通过下面的命令解决了

```js
env WINEPREFIX="$HOME/.deepinwine/Deepin-TIM" deepin-wine winecfg
```

**Comment by huming2207** [comment]
最新版的2.6.7.57似乎失效了，2k屏幕，125或者150dpi都不起作用。

系统是Manjaro，滚到了今天（20190421）最新的，桌面环境为Deepin

**Comment by hywhuangyuwei** [comment]
> 最新版的2.6.7.57似乎失效了，2k屏幕，125或者150dpi都不起作用。
> 
> 系统是Manjaro，滚到了今天（20190421）最新的，桌面环境为Deepin

Manjaro系统，Xfce桌面环境，20190425测试能修改并生效。

**Comment by pz239** [comment]
> > 最新版的2.6.7.57似乎失效了，2k屏幕，125或者150dpi都不起作用。
> > 系统是Manjaro，滚到了今天（20190421）最新的，桌面环境为Deepin
> 
> Manjaro系统，Xfce桌面环境，20190425测试能修改并生效。

同样问题，最新的manjaro xfce环境，微信修改hidpi后无效，qq正常。

**Comment by countstarlight** [comment]
@pz239 用的 `wine` 还是 `deepin-wine`

**Comment by pz239** [comment]
> @pz239 用的 `wine` 还是 `deepin-wine`
如何区分呢？用的是这个，应该是deepin-wine吧
![图片](https://user-images.githubusercontent.com/20796065/79688961-7ba61f80-8284-11ea-9b74-949d9514bf28.png)

**Comment by countstarlight** [comment]
@pz239 我不了解你安装的`wine-wechat`，你应该联系它的维护者
