### ISSUE TITLE
无法输入中文

### ISSUE THREAD

**Issue by mrbeardad** [countstarlight/deepin-wine-tim-arch#100]
系统：Manjaro20.2.1
输入框架：fcitx与fcitx5均已尝试（fcitx-sogoupinyin，fcitx-googlepinyin，fcitx5-rime）
备注：已切换至`deepin-wine`

**Comment by countstarlight** [comment]
如果系统内其他软件(浏览器，编辑软件等)能够正常使用 `fcitx`，`deepin-wine-tim` 应该也能正常输入，已经按照[Archlinux wiki](https://wiki.archlinux.org/index.php/Fcitx_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87))配置过fcitx？
> 通过` ~/.pam_environment` 设置环境变量：
> ```
> GTK_IM_MODULE DEFAULT=fcitx
> QT_IM_MODULE  DEFAULT=fcitx
> XMODIFIERS    DEFAULT=@im=fcitx
> ```

**Comment by mrbeardad** [comment]
已经设置了，我的DE是gnome，`~/.pam_environment`和`~/.xprofile`都添加了对应的配置，还是无法输入中文，但是fcitx的按键（比如切换输入法）在tim窗口中有效。  
 我以为这个版本就是有这bug，你这么一说我好像是个例呀0.0.

**Comment by countstarlight** [comment]
根据 [Archlinux wiki](https://wiki.archlinux.org/index.php/Fcitx_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87))
> GNOME 可能在某些程序中无法使用 `Ctrl + Space` 调出输入法。解决方法是修改GSettings配置：
> ```bash
> gsettings set org.gnome.settings-daemon.plugins.keyboard active false 
> ```

**Comment by mrbeardad** [comment]
设置后重登仍无效果。  
PS：不是无法调出输入法，是输入法窗口中打出的中文无法上屏到tim

**Comment by mrbeardad** [comment]
目前来看，`fcitx`、`fcitx5`、`ibus`都无法上屏中文

**Comment by mrbeardad** [comment]
deepin-wine-tim、deepin-wine-qq、deepin-wine-wechar都无法输入中文；  
而com.qq.im.deepin和deepin.com.qq.office可以输入中文

**Comment by mrbeardad** [comment]
切换wayland后，deepin-wine-wechat可以输入中文，另外两个仍然无法输入中文

**Comment by mrbeardad** [comment]
抱歉，不是wayland的原因，切换到deepin-wine5后wechat可以输入中文。但qq和tim也还是不能。

这是wechat:  
![image](https://user-images.githubusercontent.com/54128430/109411569-0c3da800-79de-11eb-8e35-2548dc09122d.png)

这是tim:
![image](https://user-images.githubusercontent.com/54128430/109411589-28414980-79de-11eb-8e9e-12f3056879b4.png)

如果您有空闲时间的话，希望能修复该bug.

**Comment by mrbeardad** [comment]
问题已解决，观察日志发现报错不支持zh_CN.UTF-8，解决步骤：
1. 编辑*/etc/locale.gen*，取消包含`zh_CN.UTF-8`那行的注释
2. `sudo locale-gen`
3. 重启

建议加入常见问题，应该有不少人只用英文吧。

**Comment by GeekEmperor** [comment]
docker用户，把宿主上/usr/share/i18n/locales/zh_CN复制过来，locale-gen之后TIM可以输入。

**Comment by whaliendev** [comment]
> 问题已解决，观察日志发现报错不支持zh_CN.UTF-8，解决步骤：
> 
> 1. 编辑*/etc/locale.gen*，取消包含`zh_CN.UTF-8`那行的注释
> 2. `sudo locale-gen`
> 3. 重启
> 
> 建议加入常见问题，应该有不少人只用英文吧。

非常感谢。同建议加入常见问题，locale选的不在国内就会出现这个问题。
