### ISSUE TITLE
QQ 安全组件异常 0x00008C01

### ISSUE THREAD

**Issue by forliuyifei** [countstarlight/deepin-wine-tim-arch#102]
![image](https://user-images.githubusercontent.com/53306807/110333725-ea3aca00-805c-11eb-8208-0f7f47c0965b.png)

![image](https://user-images.githubusercontent.com/53306807/110333558-aba50f80-805c-11eb-9736-13825a4aa669.png)

**Comment by PikaSama** [comment]
试一下重启后再打开

**Comment by countstarlight** [comment]
与 https://github.com/countstarlight/deepin-wine-tim-arch/issues/90 重复
