### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by xuelingkang** [countstarlight/deepin-wine-tim-arch#113]
环境：manjaro kde

步骤：
1. 安装deepin-wine-tim
2. 打开tim，安装tim完成并退出
3. 打开tim，安装tim完成并退出，这一步过不去，打开多少次都是一样
4. 切换到deepin-wine，使用脚本自动切换
5. 打开tim，安装tim完成并退出
6. 打开tim，提示tim组件异常，请重新下载

**Comment by countstarlight** [comment]
与 https://github.com/countstarlight/deepin-wine-tim-arch/issues/90 重复
