### ISSUE TITLE
啓動時顯示“QQ 安全組件異常，請重新下載並安裝。”

### ISSUE THREAD

**Issue by PiGiWiGi** [countstarlight/deepin-wine-tim-arch#122]
刪除了重新安裝，情況也是一樣的。
切換到wine5後，彈出一個沒有字的提示框，下面兩個按鈕（重新下載，取消）。
和wine6是一樣的，只是中間沒有字。
請問這個需要怎麼做才能解決？
謝謝

**Comment by pz239** [comment]
同样的错误,Tim无法使用

**Comment by countstarlight** [comment]
与 https://github.com/countstarlight/deepin-wine-tim-arch/issues/90 重复
