### ISSUE TITLE
小小虫：“旧版README”的链接不对

### ISSUE THREAD

**Issue by pikakolendo02** [countstarlight/deepin-wine-tim-arch#123]
当前README.md里，“旧版README”指向
https://github.com/countstarlight/deepin-wine-tim-arch/blob/16e288a7288d0d19e3fb2f7b93a3c5aa7a8f5129/run.sh
但最后的那个玩意儿应该是README.md？

**Comment by Xp-speit2018** [comment]
同问，急需解决网络问题

**Comment by countstarlight** [comment]
感谢帮助，已经更新：https://github.com/countstarlight/deepin-wine-tim-arch/commit/40bc7a59d43ca22f3a6c8c2dda33231e9ea8dae8

**Comment by countstarlight** [comment]
@Xp-speit2018 网络问题可以参照 https://github.com/countstarlight/deepin-wine-tim-arch/issues/121#issuecomment-906183510
