### ISSUE TITLE
安装完后首次可以启动，第二次就无法启动了

### ISSUE THREAD

**Issue by fjlyx97** [countstarlight/deepin-wine-tim-arch#13]
- 无论是从AUR或者是手动安装，均为第一次可以启动，重启之后再次点击图标就没有反应了

运行run.sh得到结果如下
`Deepin-TIM ./run.sh 
./run.sh:行30: _DeleteRegistry: 未找到命令
➜  Deepin-TIM 0012:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
0012:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
000f:err:service:process_send_command service protocol error - failed to write pipe!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"MountMgr" failed to start: 1053
001b:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0021:fixme:advapi:RegisterEventSourceW ((null),L"QPCore"): stub
0021:fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000000,(nil),0x0001,0x00000000,0x73fc64,(nil)): stub
0021:fixme:advapi:DeregisterEventSource (0xcafe4242) stub
0024:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
0024:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
000f:err:service:process_send_command service protocol error - failed to write pipe!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"QQFrmMgr" failed to start: 1053
0026:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
0026:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
000f:err:service:process_send_command service protocol error - failed to write pipe!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"QQProtect" failed to start: 1053
0028:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
0028:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
000f:err:service:process_send_command service protocol error - failed to write pipe!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"WineBus" failed to start: 1053
0009:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0009:fixme:winsock:WS_EnterSingleProtocolW unknown Protocol <0x00000000>
0009:fixme:winsock:WS_EnterSingleProtocolW unknown Protocol <0x00000000>
0009:fixme:ntdll:NtQueryInformationProcess (process=0xf8) Unimplemented information class: ProcessSessionInformation
0022:fixme:ntdll:NtQueryInformationProcess (process=0xb0) Unimplemented information class: ProcessSessionInformation
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
003e:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
003e:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
0017:err:service:process_send_command service protocol error - failed to write pipe!
0040:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
0040:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
0016:err:service:process_send_command service protocol error - failed to write pipe!
003c:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0022:fixme:process:WTSGetActiveConsoleSessionId stub
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84f38c
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84f38c
0049:fixme:iphlpapi:NotifyAddrChange (Handle 0x1d9fed8, overlapped 0x1d9feb8): stub
0049:fixme:iphlpapi:CancelIPChangeNotify (overlapped 0x1d9feb8): stub
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84ec24
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84ec2c
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84f468
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84f470
0022:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
0022:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
003c:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
0054:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
0054:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
0017:err:service:process_send_command service protocol error - failed to write pipe!
0056:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
0056:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
0016:err:service:process_send_command service protocol error - failed to write pipe!
003c:fixme:process:WTSGetActiveConsoleSessionId stub
003c:fixme:wtsapi:WTSQueryUserToken 1 0x33f81c
003c:fixme:wtsapi:WTSQueryUserToken 1 0x33f81c
003c:fixme:ntdll:NtQueryInformationProcess (process=0x84) Unimplemented information class: ProcessSessionInformation
0022:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x84f1e8 1 C) semi-stub
0022:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x84efd8 1 C) semi-stub
005d:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
005d:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
0017:err:service:process_send_command service protocol error - failed to write pipe!
005f:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
005f:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
0016:err:service:process_send_command service protocol error - failed to write pipe!
0022:fixme:crypt:CryptProtectMemory (0x187290 112 00000001): stub
0022:fixme:crypt:CryptUnprotectMemory (0x10e07e0 112 00000001): stub
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84c768
003c:fixme:msvcrt:__clean_type_info_names_internal (0x10116fb4) stub
003c:fixme:msvcrt:__clean_type_info_names_internal (0x3ce33c) stub
003c:fixme:msvcrt:__clean_type_info_names_internal (0x30283754) stub
003c:fixme:msvcrt:__clean_type_info_names_internal (0x3f34ec) stub
003c:fixme:msvcrt:__clean_type_info_names_internal (0x1101d33c) stub
003c:fixme:msvcrt:__clean_type_info_names_internal (0x11f1138c) stub
003c:fixme:msvcrt:__clean_type_info_names_internal (0x56fc34) stub
003c:fixme:msvcrt:__clean_type_info_names_internal (0x11114564) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x513fe5ec) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x576721b4) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x52f118a4) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x50e5afa4) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x505d47fc) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x57af939c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x50128aa4) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x535e8cb4) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x5458444c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x51476394) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x534083cc) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x57eb139c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x52a32744) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x5141d37c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x5394c344) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x539a2b1c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x539cd34c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x57e6c39c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x513d408c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x51dc276c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x537291a4) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x5137c4ac) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x5762a62c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x5143335c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x514924cc) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x57a3356c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x5377d33c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x5802137c) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x53a4e624) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x53a24794) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x52885394) stub
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84e90c
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84e934
0022:fixme:msvcrt:__clean_type_info_names_internal (0x2110454) stub
0022:fixme:msvcrt:__clean_type_info_names_internal (0x10116fb4) stub
0022:fixme:msvcrt:__clean_type_info_names_internal (0x3ce33c) stub
0021:fixme:advapi:RegisterEventSourceW ((null),L"QPCore"): stub
0021:fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000000,(nil),0x0001,0x00000000,0x73fc80,(nil)): stub
0021:fixme:advapi:DeregisterEventSource (0xcafe4242) stub
001b:fixme:msvcrt:__clean_type_info_names_internal (0x30283754) stub
001b:fixme:msvcrt:__clean_type_info_names_internal (0x3f34ec) stub
001b:fixme:msvcrt:__clean_type_info_names_internal (0x1101d33c) stub
001b:fixme:msvcrt:__clean_type_info_names_internal (0x11f1138c) stub
001b:fixme:msvcrt:__clean_type_info_names_internal (0x89fc34) stub
001b:fixme:msvcrt:__clean_type_info_names_internal (0x11114564) stub
`

-  Wine的版本为3.7
`➜  Deepin-TIM wine --version
wine-3.7
`

**Comment by countstarlight** [comment]
没有看到有特别的错误，多等一会试试?

**Comment by fjlyx97** [comment]
@countstarlight 我试过好多次了，多等一会儿也是没反应，不懂问题在哪。我同样试过deepin-qq-im，这个也是只有第一次安装可以使用，第二次也是无法打开，运行run.sh会报报错：~/.deepinwine/Deepin-QQ/drive_c/deepin/EnvInit.sh 找不到这个文件，和TIM这个报错似乎不大一样

**Comment by countstarlight** [comment]
没有找到`EnvInit.sh`是因为deepin新版的包整合启动参数到一起了，它的维护者也许没有调整，试试`deepin-wine-qq`:
```shell
yaourt deepin-wine-qq
```
前几次启动会提示qq保护组件什么的没有安装，等一会或重启一下就好了。

**Comment by fjlyx97** [comment]
deepin-wine-qq确实可以直接使用，终于找到了一个稳定的QQ替代品了，万分感谢

**Comment by problem233** [comment]
同有这个问题，我发现遇到这个问题时运行 `WINEPREFIX=$HOME/.deepinwine/Deepin-TIM winecfg` 然后什么都不用做直接关闭，再运行 `/opt/deepinwine/apps/Deepin-TIM/run.sh` 就能正常启动。原理不明。

**Comment by ystyle** [comment]
同样的问题， 不知道为什么 
```text
ystyle@archlinux  ~  /opt/deepinwine/apps/Deepin-TIM/run.sh
/opt/deepinwine/apps/Deepin-TIM/run.sh:行30: _DeleteRegistry：未找到命令
 ystyle@archlinux  ~  0012:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
0012:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
000f:err:service:process_send_command service protocol error - failed to write pipe!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"MountMgr" failed to start: 1053
001b:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0021:fixme:advapi:RegisterEventSourceW ((null),L"QPCore"): stub
0021:fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000000,(nil),0x0001,0x00000000,0x73fc64,(nil)): stub
0021:fixme:advapi:DeregisterEventSource (0xcafe4242) stub
0024:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
0024:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
000f:err:service:process_send_command service protocol error - failed to write pipe!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"QQFrmMgr" failed to start: 1053
0026:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
0026:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
000f:err:service:process_send_command service protocol error - failed to write pipe!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"QQProtect" failed to start: 1053
0028:err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
0028:err:module:attach_dlls Importing dlls for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
000f:err:service:process_send_command service protocol error - failed to write pipe!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"WineBus" failed to start: 1053
0009:fixme:ntdll:EtwEventRegister ({dc55d4d9-138d-441a-80cb-77aec617e2db}, 0x407d60, 0x40fa10, 0x40fa40) stub.
0009:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0009:err:winediag:wined3d_dll_init Setting maximum allowed wined3d GL version to 0.12290.
0009:fixme:win:EnumDisplayDevicesW ((null),0,0x32eb34,0x00000000), stub!
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  194
  Current serial number in output stream:  198
0022:fixme:process:NtQueryInformationProcess (process=0xb0) Unimplemented information class: ProcessSessionInformation
0022:fixme:msg:ChangeWindowMessageFilter 4a 00000001
0035:fixme:iphlpapi:NotifyAddrChange (Handle 0x1d9fed8, overlapped 0x1d9feb8): stub
0035:fixme:iphlpapi:CancelIPChangeNotify (overlapped 0x1d9feb8): stub
0022:fixme:process:WTSGetActiveConsoleSessionId stub
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84f4bc semi-stub!
0022:fixme:shell:_SHGetUserProfilePath unsupported for user other than current or default
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84f4c4 semi-stub!
0022:fixme:shell:_SHGetUserProfilePath unsupported for user other than current or default
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84f468 semi-stub!
0022:fixme:shell:_SHGetUserProfilePath unsupported for user other than current or default
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84f470 semi-stub!
0022:fixme:shell:_SHGetUserProfilePath unsupported for user other than current or default
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84f468 semi-stub!
0022:fixme:shell:_SHGetUserProfilePath unsupported for user other than current or default
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84f470 semi-stub!
0022:fixme:shell:_SHGetUserProfilePath unsupported for user other than current or default
0022:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
0022:fixme:ntdll:EtwEventRegister ({dc55d4d9-138d-441a-80cb-77aec617e3f7}, 0x10097970, 0x10116b98, 0x10116b90) stub.
0022:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0022:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x84f1e8 1 C) semi-stub
0022:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x84efc8 1 C) semi-stub
0022:err:rpc:I_RpcGetBuffer no binding
0022:fixme:crypt:CryptProtectMemory (0x178678 112 00000001): stub
0022:fixme:crypt:CryptUnprotectMemory (0x10dc070 112 00000001): stub
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84c758 semi-stub!
0022:fixme:shell:_SHGetUserProfilePath unsupported for user other than current or default
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84e90c semi-stub!
0022:fixme:shell:_SHGetUserProfilePath unsupported for user other than current or default
0022:fixme:wtsapi:WTSQueryUserToken 1 0x84e934 semi-stub!
0022:fixme:shell:_SHGetUserProfilePath unsupported for user other than current or default
0021:fixme:advapi:RegisterEventSourceW ((null),L"QPCore"): stub
0021:fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000000,(nil),0x0001,0x00000000,0x73fc80,(nil)): stub
0021:fixme:advapi:DeregisterEventSource (0xcafe4242) stub

```
