### ISSUE TITLE
睡眠之后重新开机，Tim无法重新上线

### ISSUE THREAD

**Issue by Penguinang** [countstarlight/deepin-wine-tim-arch#14]
睡眠之后，重新开机，Tim无法上线，手动设置状态时，会弹出消息框 `登录超时，请检查您的网络或者本机防火墙设置`，然而检查发现网络的确是没有问题的。退出Tim重新启动一次可以解决，不过有点麻烦。

**Comment by countstarlight** [comment]
这个是已知问题，参见[issue12](https://github.com/countstarlight/deepin-wine-tim-arch/issues/12)，我之后添加到readme.

**Comment by Penguinang** [comment]
好的
