### ISSUE TITLE
X Error of failed request: BadWindow

### ISSUE THREAD

**Issue by RayneHwang** [countstarlight/deepin-wine-tim-arch#15]
```
$ env WINEPREFIX=/home/xxx/.deepinwine/Deepin-TIM deepin-wine 'c:\Program Files\Tencent\TIM\Bin\TIM.exe'

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x0
  Serial number of failed request:  10

  Current serial number in output stream:  10
```
![screenshot_20180912_172554](https://user-images.githubusercontent.com/6406592/45416518-b0b6bd00-b6b2-11e8-9739-e21dfa1132d3.png)

操作系统：
![screenshot_20180912_174039](https://user-images.githubusercontent.com/6406592/45416656-00958400-b6b3-11e8-83d6-b83a68c72827.png)

**Comment by RayneHwang** [comment]
> 试试运行
> 
> ```shell
> /opt/deepinwine/apps/Deepin-TIM/run.sh
> ```
> 
> 用`deepin-wine`没有测试过，记得AUR源里有一个依赖`deepin-wine`的tim打包

感谢回复，我就是执行的`/opt/deepinwine/apps/Deepin-TIM/run.sh`，这个脚本最终也是调用的`env WINEPREFIX=/home/xxx/.deepinwine/Deepin-TIM deepin-wine 'c:\Program Files\Tencent\TIM\Bin\TIM.exe'`来运行

**Comment by countstarlight** [comment]
已经安装有`wine`吗?` run.sh`里的调用的是`wine`而不是`deepin-wine`，
试试把调用命令里的`deepin-wine`改为`wine`

**Comment by RayneHwang** [comment]
抱歉，这个bug是AUR里面[另一个package](https://aur.archlinux.org/packages/deepin.com.qq.office/)的问题，它用的是deepin-wine。这几天一直折腾tim都弄混了。
使用deepin-wine-tim的问题仍然是gdi32.dll failed to initialize，我去 #10 append一下，这个先关闭了。
再次感谢维护！
