### ISSUE TITLE
网络连接状态改变后连接超时的问题能否解决？

### ISSUE THREAD

**Issue by L-Ryland** [countstarlight/deepin-wine-tim-arch#19]

**Comment by countstarlight** [comment]
这个问题暂时没办法解决，之后有空我会尝试移植deepin-wine/tools来实现

**Comment by countstarlight** [comment]
现在可以通过[自动切换](https://github.com/countstarlight/deepin-wine-tim-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2)切换到 `deepin-wine` 解决
