### ISSUE TITLE
ctrl+alt+z 快捷键

### ISSUE THREAD

**Issue by EricDracula** [countstarlight/deepin-wine-tim-arch#2]
当使用ctrl+alt+z隐藏面板后，再使用ctrl+alt+z无法重现面板，我这里来了消息也不管用。
PS. 希望视频和音频的功能能被大神们补上！

**Comment by countstarlight** [comment]
2.3已经修复音频功能，其他的问题正在尝试解决

**Comment by EricDracula** [comment]
已经更新到2.3了。关于那个快捷键，主要是我之前没有注意到截图里的这个窗口。启动Tim后，就会有这个窗口，在这个窗口active的情况下Tiim的快捷键例如ctrl+alt+z才会管用。但是这个窗口不能最大化也不能最小化不是很美观和方便，或许可以将其隐藏或者将其集成到右上角的那一栏里。
![screenshot from 2017-12-04 19-16-13](https://user-images.githubusercontent.com/9444299/33550109-b728f5b8-d927-11e7-898c-3b360318dfae.png)

**Comment by yinflying** [comment]
@EricDracula  快捷键可以使用xdotool解决。可参见：[wine下安装QQ轻聊版](http://yinflying.top/2016/09/192) 3.3节，窗口化问题可参见3.5节。

**Comment by EricDracula** [comment]
@yinflying 谢谢啦，解决了。Gnome窗口化的问题需要一个TopIcons的Gnome插件。

**Comment by yinflying** [comment]
@EricDracula 感谢告知，已更新博文。

**Comment by kmvan** [comment]
截图flameshot，你值得拥有
