### ISSUE TITLE
升级wine4.0RC后，图形界面反应异常慢

### ISSUE THREAD

**Issue by specter119** [countstarlight/deepin-wine-tim-arch#20]
系统: Arch

貌似是wine 升级到了4.0rc以后产生的问题。
托盘鼠标长时间驻留显示状态(反应较快)，右键可以点，反应需要等待很久。
主界面也可以点，反应也需要等待很久。
以上说的反应等待很久，就是半分钟到一分多钟的样子。

尝试过重装，没有作用。

还没有尝试降级wine。

---update---

尝试降级wine到3.9.1,3.8.1(删除~/.deepinwine)重新安装deepin-wine-tim-arch，安装正常后，软件启动不起来了。

**Comment by countstarlight** [comment]
我也遇到了，QQ和TIM反应都异常慢，我去找找问题。

**Comment by XanthusL** [comment]
wine4.0 cpu占用很高， 降级后就好了。

无法启动，我今天遇到了。发现微信企业版一直正常，因为用的deepin-wine, TIM用的wine

`/opt/deepinwine/apps/Deepin-TIM/run.sh`中
```sh
# WINE_CMD="wine"
WINE_CMD="deepin-wine"
```
用deepin-wine换掉wine 启动成功了。

**Comment by Core00077** [comment]
wine downgrade 到3.21-1版本可用。把tim删除干净了之后先downgrade wine到3.21-1，然后安装tim可以正常使用

**Comment by countstarlight** [comment]
wine-4.0-rc3看起来已经修复了这个问题，内存占用和反应速度和之前一样。

**Comment by specter119** [comment]
> wine-4.0-rc3看起来已经修复了这个问题，内存占用和反应速度和之前一样。

是的，看了你们的回复后，发现 4.0-rc3 使用正常，那这个issue关掉了。
