### ISSUE TITLE
DDE 下托盘图标无法响应鼠标事件

### ISSUE THREAD

**Issue by chenjunyu19** [countstarlight/deepin-wine-tim-arch#21]
如题，无论左键或是右键都没有反应，有时候一不小心关闭主窗口就很糟心了。

- `deepin-wine-tim` 2.1.5-4
- `wine` 4.0 rc3-1
- `deepin-dock` 4.8.4.1-1

**Comment by chenjunyu19** [comment]
> 降级wine到低版本试试，如果低版本没有这个问题，应该是dde还没有支持最新的wine。

好早以前就有这个问题了，不是 wine 版本的缘故。

**Comment by arslan2012** [comment]
+1我也出现了这个问题，也是用的deepin桌面

**Comment by TTcheng** [comment]
最新版问题仍然重现，而另外一个包deepin.com.qq.office则没有这样的问题

**Comment by Core00077** [comment]
KDE平台也有这个问题，只是不是一启动就出现，而是过一段时间后（例如锁定屏幕后），托盘会无法响应鼠标事件。
- deepin-wine-tim 2.3.1_3-5
- wine 4.2-1
- KDE plasma 5.15.0

**Comment by jerrylususu** [comment]
补充一个KDE下的特殊情况：如果是双屏幕配置，且主屏幕在右侧，托盘区域在左侧，就会导致TIM/QQ的托盘图标无法响应点击事件（左键/右键均无反应）。这似乎是一个deepin-wine的问题，和屏幕坐标相关，在深度论坛上也早有反馈，但至今未有修复。
如果遇到了，一个可用的解决方案是把主屏幕设定到左侧屏幕，即可保证坐标恒为正值，也就可以点击了。

**Comment by countstarlight** [comment]
现在可以通过[自动切换](https://github.com/countstarlight/deepin-wine-tim-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2)切换到 `deepin-wine` 解决
