### ISSUE TITLE
KDE 微信阴影窗口置顶

### ISSUE THREAD

**Issue by xz-dev** [countstarlight/deepin-wine-tim-arch#22]
KDE 环境下，阴影窗口置于最顶端，且无法关闭  
![default](https://user-images.githubusercontent.com/32761048/51530967-1a23b500-1e77-11e9-8139-97b3b5e997e4.png)

**Comment by kmvan** [comment]
很多exe都是这样，例如网易音乐等。很奇怪这个阴影。

**Comment by kmvan** [comment]
> gnome也会，解决方案是，把它放到另一个工作区

有消息来了会不知道

**Comment by ystyle** [comment]
@kmvan 我这会有一个gnome全局提示的[wine windows program loader]的消息， 虽然不知道具体是什么 。。。。

**Comment by xz-dev** [comment]
deepin-wine 已支持 kde，请测试并升级 https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/12#issuecomment-459973338

**Comment by yangon99** [comment]
有个解决方法是，把窗口最小化之后再还原

**Comment by xz-dev** [comment]
使用 deepin-wine 替换 wine 即可避免该错误
编辑文件 <code>/opt/deepinwine/apps/Deepin-WeChat/run.sh</code>
把 <code>WINE_CMD="wine"</code> 改为<code>WINE_CMD="deepin-wine"
</code>
添加 [archlinuxcn 源](https://github.com/archlinuxcn/mirrorlist-repo)安装deepin-wine
deepin-wine 在KDE环境中的运行方法：https://extendswind.top/posts/technical/deepin_wine_run_in_not_gnome_desktop_environment/
deepin-wine 在GNOME 环境下可以直接安装运行

**Comment by countstarlight** [comment]
现在 `deepin-wine-wechat` 可以通过[自动切换](https://github.com/countstarlight/deepin-wine-wechat-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2)切换到 `deepin-wine` 解决
