### ISSUE TITLE
i3没有快捷方式怎么继续安装

### ISSUE THREAD

**Issue by eocene317** [countstarlight/deepin-wine-tim-arch#30]

**Comment by countstarlight** [comment]
运行命令：
```shell
/opt/deepinwine/apps/Deepin-TIM/run.sh
````
注意，根据[Archlinux wiki](https://wiki.archlinux.org/index.php/Tencent_QQ_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#Wine)，在平铺式窗口管理器下，样式可能会出现大规模失控
