### ISSUE TITLE
TIM 2.3.2 开启时间久了后，打开群公告或群文件，会崩溃。

### ISSUE THREAD

**Issue by kmvan** [countstarlight/deepin-wine-tim-arch#31]
![image](https://user-images.githubusercontent.com/3839554/55684587-29e36d80-597f-11e9-99e1-b6777b957906.png)

大概开启时间在2个小时以上后，点击群公告或群文件（web内容？），然后会卡10秒，然后崩溃了。不知道大家有没有试过这个情况？

**Comment by Core00077** [comment]
同样有这个问题，目前测试的感觉的确主要是web内容……应该是连接超时引起的，不过老实说我不觉得是这个仓库的问题，windows下原生的tim也有，只不过大多数情况下windows下不会连接超时？

不过感觉并不太影响使用，一般我会x掉

**Comment by kmvan** [comment]
> 同样有这个问题，目前测试的感觉的确主要是web内容……应该是连接超时引起的，不过老实说我不觉得是这个仓库的问题，windows下原生的tim也有，只不过大多数情况下windows下不会连接超时？
> 
> 不过感觉并不太影响使用，一般我会x掉

x不掉，一查看那些内容就崩溃。例如添加好友信息或加群信息之类的。

**Comment by Core00077** [comment]
目前的办法也只有重开了。我个人倾向于这个问题属于上游，windows平台下的tim有时候也会连接超时引起崩溃。作者做的工作是将deepin的wine容器打包过来做了些arch的适配，所以考虑向wine或者tim这样的上游反映会更好。
当然这只是个人看法，可以等作者给个答复。

**Comment by kmvan** [comment]
> 目前的办法也只有重开了。我个人倾向于这个问题属于上游，windows平台下的tim有时候也会连接超时引起崩溃。作者做的工作是将deepin的wine容器打包过来做了些arch的适配，所以考虑向wine或者tim这样的上游反映会更好。
> 当然这只是个人看法，可以等作者给个答复。

But...`deepin.com.qq.office` 这个2.0版本的TIM倒是没有这个情况，或许是版本问题吧。当然能用2.3版已经很幸福了，感谢。

**Comment by lelelemonade** [comment]
我开5分钟就出现这个了，只能重新登录

**Comment by kmvan** [comment]
貌似找到方法解决了。
开着 TIM 的设置窗口，一直挂在后台。经测试，2.3.2 版本 TIM 放了，并且切换到有 web 内容的界面，也不会崩溃了。
猜测是设置框有 web 内容，一直展示的话就可以让某些线程常驻，在其他地方打开 web 内容的界面，不需要经过重建，从而绕过了重建时候处罚的 bug 导致崩溃的问题。

**Comment by Core00077** [comment]
新发现，根据作者readme的提示，更换了wine为deepin-wine，同样有这个问题，而且这次复现率为100%，以至于下载文件、群公告等都无法正常使用。
还好wine4.19马上出来就能解决tim的问题了，之后再用回来官方wine看看情况
