### ISSUE TITLE
deepin-wine-tim下载后安装后的问题

### ISSUE THREAD

**Issue by debugbb** [countstarlight/deepin-wine-tim-arch#36]
用yay -S 可以正常下载，也打开了安装界面，正常安装完成，安装完成后，也打开了，至此没有问题。
但是退出之后想再次启动，却打不开了，没有反应。
系统是manjaro18.11，kde桌面
也按照说明改成deepin-wine启动了
请问如何解决？
deepin-wine-wechat也是同样的问题
谢谢

**Comment by countstarlight** [comment]
参照 https://github.com/countstarlight/deepin-wine-wechat-arch/issues/27 修改试试

**Comment by debugbb** [comment]
试过了，还是一样的，安装完是能启动使用的，但是关掉后，再打开，还是没有反应

**Comment by debugbb** [comment]
@countstarlight 已经解决，安装路径的问题，我在你关联的issue中说明了，我在这里也加上，顺手close，谢谢！
-----------------------------------------------------------------------------------------------------------------------------------
解决了，总算搞定了，因为我安装的时候，更换了安装路径
如果更换了安装路径，请复制一下安装界面中识别出来的路径，然后一定记着去run.sh中把以下更换成更换后的路径（大约在32行）：
env WINEPREFIX="$WINEPREFIX" WINEDEBUG=-msvcrt $WINE_CMD **"Z:\home\xxx\apps\wechat\\WeChat.exe"** &
