### ISSUE TITLE
最新版的无法输入中文

### ISSUE THREAD

**Issue by Jontyshaw** [countstarlight/deepin-wine-tim-arch#38]
系统环境：Linux  5.3.8-3-MANJARO #1 SMP PREEMPT Sun Nov 3 14:19:23 UTC 2019 x86_64 GNU/Linux
输入法：fcitx-rime
具体问题：在tim下无法切换到中文输入法

**Comment by countstarlight** [comment]
降级wine到4.16 https://github.com/countstarlight/deepin-wine-wechat-arch/issues/31

**Comment by archyly** [comment]
升级到最新的wine 4.20已经没有问题了
