### ISSUE TITLE
tim无法启动

### ISSUE THREAD

**Issue by Jontyshaw** [countstarlight/deepin-wine-tim-arch#39]
最新版的deepin-wine-tim第一次安装还能启动，但是把它关掉，以后总是无法启动。除非删除tim的配置文件。（系统：manjaro 18.1.3 wine：4.18.1），

**Comment by time-and-fate** [comment]
Arch Linux，wine 4.18 遇到了一样的问题

想请问一下具体是删除哪个文件呢？

**Comment by archyly** [comment]
升级wine到最新版本，已经可以正常运行
