### ISSUE TITLE
env: ‘deepin-wine’: No such file or directory

### ISSUE THREAD

**Issue by promach** [countstarlight/deepin-wine-tim-arch#4]
> [promach@archlinux ~]$ /opt/deepinwine/apps/Deepin-TIM/run.sh
[promach@archlinux ~]$ env: ‘deepin-wine’: No such file or directory
^C
[promach@archlinux ~]$ pacman -Qo /opt/deepinwine/apps/Deepin-TIM/run.sh
/opt/deepinwine/apps/Deepin-TIM/run.sh is owned by deepin-wine-tim 2.0.0-2.3
[promach@archlinux ~]$ 

What step did I miss before I start the run.sh ?

**Comment by countstarlight** [comment]
How do you install it? List the commands you entered when installing.

**Comment by promach** [comment]
yaourt -S deepin-wine-tim

**Comment by countstarlight** [comment]
Sorry, I do not know what the problem is. This afternoon I installed archlinux on a virtual machine, upgraded to the latest, and then installed `deepin-wine-tim` with `yaourt`, it worked without mistakes. Maybe this problem is related to something else you modified.

**Comment by promach** [comment]
It only works the **first time** I use TIM.

It could not be started after computer reboots

**Comment by countstarlight** [comment]
Oh, I got it. On the first time, it is tim's installation interface (the `立即安装` button below the QR Code may not be displayed) and you will need to click on it and complete the installation process.

**Comment by promach** [comment]
I can login to my QQ account and send message the first time I use TIM.

After computer reboots, I could not even start TIM

**Comment by countstarlight** [comment]
Check if the `WINE_CMD` in your `～/.deepinwine/Deepin-TIM/drive_c/deepin/EnvInit.sh` file is `deepin-wine`, if it is, change it to `wine`:
```diff
- WINE_CMD="deepin-wine"
+ WINE_CMD="wine"

```

**Comment by promach** [comment]
I have changed to WINE_CMD="wine"  , but I am getting the following error:

`[promach@archlinux ~]$ /opt/deepinwine/apps/Deepin-TIM/run.sh
[promach@archlinux ~]$ fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
err:module:load_builtin_dll failed to load .so lib for builtin L"l3codeca.acm": libmpg123.so.0: cannot open shared object file: No such file or directory
fixme:ntdll:NtQueryInformationProcess (process=0x108) Unimplemented information class: ProcessSessionInformation
fixme:exec:SHELL_execute flags ignored: 0x00000100
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
err:module:load_builtin_dll failed to load .so lib for builtin L"l3codeca.acm": libmpg123.so.0: cannot open shared object file: No such file or directory
fixme:msvcrt:__clean_type_info_names_internal (0x52d008a4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50db9174) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50569a74) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50126a94) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5379ebc4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x561c444c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x513d6394) stub
fixme:msvcrt:__clean_type_info_names_internal (0x535d83cc) stub
fixme:msvcrt:__clean_type_info_names_internal (0x56f1139c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5283273c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5137d37c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x555ac344) stub
fixme:msvcrt:__clean_type_info_names_internal (0x55602b1c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5562d34c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x56ecc39c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5133408c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x51d0e744) stub
fixme:msvcrt:__clean_type_info_names_internal (0x555491a4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x512dc4ac) stub
fixme:msvcrt:__clean_type_info_names_internal (0x566fa62c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5139335c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x513f24cc) stub
fixme:msvcrt:__clean_type_info_names_internal (0x56ab356c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5557d33c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5708137c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x556ae624) stub
fixme:msvcrt:__clean_type_info_names_internal (0x55684794) stub
fixme:msvcrt:__clean_type_info_names_internal (0x52685394) stub
^C
[promach@archlinux ~]$ 
`

**Comment by countstarlight** [comment]
Ignore these errors and wait for a while. Can tim work?

**Comment by promach** [comment]
> Ignore these errors and wait for a while. Can tim work?

No, nothing happened. TIM does not start.

**Comment by promach** [comment]
@countstarlight I have updated the error log in the comment above. I still could not get your TIM working.  Could you reproduce the similar issue using real installation of Arch Linux, not using virtual machine environment ?

**Comment by nemolus** [comment]
Hi, 
I have a very similar (or maybe the same) problem:
1. that it runs OK after installation;
2. but after a reboot, it won't start. 

If I uninstall it and reinstall it, the same happens: 
1. it runs again after installation;
2. but it fails to start after a reboot.

Errors:
`/opt/deepinwine/apps/Deepin-TIM/run.sh
err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
err:service:process_send_command service protocol error - failed to write pipe!
fixme:service:scmdatabase_autostart_services Auto-start service L"MountMgr" failed to start: 1053
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:advapi:RegisterEventSourceW ((null),L"QPCore"): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000000,(nil),0x0001,0x00000000,0x72fc14,(nil)): stub
fixme:advapi:DeregisterEventSource (0xcafe4242) stub
err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
err:service:process_send_command service protocol error - failed to write pipe!
fixme:service:scmdatabase_autostart_services Auto-start service L"QQFrmMgr" failed to start: 1053
err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
err:service:process_send_command service protocol error - failed to write pipe!
fixme:service:scmdatabase_autostart_services Auto-start service L"QQProtect" failed to start: 1053
err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
err:service:process_send_command service protocol error - failed to write pipe!
fixme:service:scmdatabase_autostart_services Auto-start service L"WineBus" failed to start: 1053
err:module:load_builtin_dll failed to load .so lib for builtin L"l3codeca.acm": libmpg123.so.0: cannot open shared object file: No such file or directory
fixme:ntdll:NtQueryInformationProcess (process=0xa8) Unimplemented information class: ProcessSessionInformation
reg: The system was unable to find the specified registry key or value
[meng@MBP ~]$ fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
err:module:load_builtin_dll failed to load .so lib for builtin L"l3codeca.acm": libmpg123.so.0: cannot open shared object file: No such file or directory
err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
err:service:process_send_command service protocol error - failed to write pipe!
err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
err:service:process_send_command service protocol error - failed to write pipe!
fixme:ntdll:NtQueryInformationProcess (process=0xf4) Unimplemented information class: ProcessSessionInformation
fixme:process:WTSGetActiveConsoleSessionId stub
fixme:wtsapi:WTSQueryUserToken 1 0x82f34c
fixme:wtsapi:WTSQueryUserToken 1 0x82f34c
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
fixme:iphlpapi:NotifyAddrChange (Handle 0x1c2fe94, overlapped 0x1c2fe74): stub
fixme:iphlpapi:CancelIPChangeNotify (overlapped 0x1c2fe74): stub
fixme:wtsapi:WTSQueryUserToken 1 0x82f478
fixme:wtsapi:WTSQueryUserToken 1 0x82f480
fixme:exec:SHELL_execute flags ignored: 0x00000100
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
err:module:load_builtin_dll failed to load .so lib for builtin L"l3codeca.acm": libmpg123.so.0: cannot open shared object file: No such file or directory
fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
err:service:process_send_command service protocol error - failed to write pipe!
err:module:import_dll Library ntoskrnl.exe (which is needed by L"C:\\windows\\system32\\winedevice.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\system32\\winedevice.exe" failed, status c0000135
err:service:process_send_command service protocol error - failed to write pipe!
fixme:process:WTSGetActiveConsoleSessionId stub
fixme:wtsapi:WTSQueryUserToken 1 0x33f7cc
fixme:wtsapi:WTSQueryUserToken 1 0x33f7cc
fixme:ntdll:NtQueryInformationProcess (process=0x7c) Unimplemented information class: ProcessSessionInformation
fixme:wtsapi:WTSQueryUserToken 1 0x82f428
fixme:wtsapi:WTSQueryUserToken 1 0x82f430
fixme:wtsapi:WTSQueryUserToken 1 0x82f428
fixme:wtsapi:WTSQueryUserToken 1 0x82f430
fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
fixme:msvcrt:__clean_type_info_names_internal (0x10116fb4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x3cd2cc) stub
fixme:msvcrt:__clean_type_info_names_internal (0x30283754) stub
fixme:msvcrt:__clean_type_info_names_internal (0x3f34ec) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1101d33c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x11f1138c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x56fc34) stub
fixme:msvcrt:__clean_type_info_names_internal (0x11114564) stub
fixme:msvcrt:__clean_type_info_names_internal (0x52d008a4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50db9174) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50569a74) stub
fixme:msvcrt:__clean_type_info_names_internal (0x50126a94) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5379ebc4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x561c444c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x513d6394) stub
fixme:msvcrt:__clean_type_info_names_internal (0x535d83cc) stub
fixme:msvcrt:__clean_type_info_names_internal (0x56f1139c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5283273c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5137d37c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x555ac344) stub
fixme:msvcrt:__clean_type_info_names_internal (0x55602b1c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5562d34c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x56ecc39c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5133408c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x51d0e744) stub
fixme:msvcrt:__clean_type_info_names_internal (0x555491a4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x512dc4ac) stub
fixme:msvcrt:__clean_type_info_names_internal (0x566fa62c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5139335c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x513f24cc) stub
fixme:msvcrt:__clean_type_info_names_internal (0x56ab356c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5557d33c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x5708137c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x556ae624) stub
fixme:msvcrt:__clean_type_info_names_internal (0x55684794) stub
fixme:msvcrt:__clean_type_info_names_internal (0x52685394) stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x82f1a8 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x82ef98 1 C) semi-stub
[meng@MBP ~]$ fixme:wtsapi:WTSQueryUserToken 1 0x82e8c8
fixme:wtsapi:WTSQueryUserToken 1 0x82e8f0
fixme:msvcrt:__clean_type_info_names_internal (0xa770454) stub
fixme:msvcrt:__clean_type_info_names_internal (0x10116fb4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x3cd2cc) stub
fixme:advapi:RegisterEventSourceW ((null),L"QPCore"): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000000,(nil),0x0001,0x00000000,0x72fc30,(nil)): stub
fixme:advapi:DeregisterEventSource (0xcafe4242) stub
fixme:msvcrt:__clean_type_info_names_internal (0x30283754) stub
fixme:msvcrt:__clean_type_info_names_internal (0x3f34ec) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1101d33c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x11f1138c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x86fc34) stub
fixme:msvcrt:__clean_type_info_names_internal (0x11114564) stub
`

**Comment by countstarlight** [comment]
@nemolus @promach I reinstalled archlinux and gnome (kde before), everything worked fine, did you install the package `base-devel`?
```shell
sudo pacman -S base-devel
```
