### ISSUE TITLE
无法加载图片&头像

### ISSUE THREAD

**Issue by problem233** [countstarlight/deepin-wine-tim-arch#42]
Arch/i3wm,wine 5.1，无法加载用户/群头像，聊天图片无法加载。

错误 log 应该是这个：
```
0093:fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
```

**Comment by countstarlight** [comment]
没有在`i3wm`上测试过，上述log应该只会导致不能保存密码和自动登录，卸载重新安装或换用[deepin-wine-qq-arch](https://github.com/countstarlight/deepin-wine-qq-arch)试试

**Comment by Hulenkius** [comment]
我通过下列命令解决
```
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
```

**Comment by Core00077** [comment]
在原生wine下的确存在这个问题，禁用ipv6的确可以解决，但如果本身自己要用ipv6就比较麻烦，建议像[另一个issue](https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/222#issuecomment-602055550) 里这样做一个本地代理。然后登录tim的时候右上角设置，选择对应的代理（看不见选项可以按tab或者上下左右键）。目前自己使用非常稳定

**Comment by problem233** [comment]
@Core00077 感谢指路（
