### ISSUE TITLE
无法找到主程序

### ISSUE THREAD

**Issue by chengnan049** [countstarlight/deepin-wine-tim-arch#45]
Arch-70233% /opt/deepinwine/apps/Deepin-TIM/run.sh   
Arch-70233% wine: cannot find 'c:\Program Files\Tencent\TIM\Bin\TIM.exe'

(gsd-xsettings:4752): xsettings-plugin-WARNING **: 23:25:52.033: You can only run one xsettings manager at a time; exiting
Failed to start: Could not initialize xsettings manager.

启动日志如上

**Comment by countstarlight** [comment]
在安装tim时修改了默认安装路径？https://github.com/countstarlight/deepin-wine-tim-arch/issues/44

**Comment by WalkerinGitHub** [comment]
直接安装的

**Comment by WalkerinGitHub** [comment]
QQ现在也是这个状况,这是第一次运行
Arch-70233% /opt/deepinwine/apps/Deepin-QQ/run.sh
Arch-70233% 
(gsd-xsettings:5928): xsettings-plugin-WARNING **: 23:46:42.604: You can only run one xsettings manager at a time; exiting
Failed to start: Could not initialize xsettings manager.
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18

**Comment by WalkerinGitHub** [comment]
> 在安装tim时修改了默认安装路径？#44

直接安装的

**Comment by countstarlight** [comment]
> QQ现在也是这个状况,这是第一次运行
> Arch-70233% /opt/deepinwine/apps/Deepin-QQ/run.sh
> Arch-70233%
> (gsd-xsettings:5928): xsettings-plugin-WARNING **: 23:46:42.604: You can only run one xsettings manager at a time; exiting
> Failed to start: Could not initialize xsettings manager.
> wine: cannot find L"C:\windows\system32\winemenubuilder.exe"
> wine version: 2.18

`wine`版本是2.18?

**Comment by WalkerinGitHub** [comment]
> > QQ现在也是这个状况，这是第一次运行
> > Arch-70233％/opt/deepinwine/apps/Deepin 
> > - QQ/run.sh Arch-70233％
> > （gsd-xsettings：5928）：xsettings-plugin-WARNING **： 23：46：42.604：您一次只能运行一个xsettings管理器；退出
> > 无法启动：无法初始化xsettings管理器。
> > wine：找不到L“ C：\ windows \ system32 \ winemenubuilder.exe” 
> > wine版本：2.18
> 
> `wine`版本是2.18？

是的,需要我换版本吗?

**Comment by countstarlight** [comment]
你的系统是 Archlinux吗，Archlinux上wine最新的版本是 `5.4`，wine版本过旧可能不支持

**Comment by WalkerinGitHub** [comment]
> 你的系统是 Archlinux吗，Archlinux上wine最新的版本是 `5.4`，wine版本过旧可能不支持
是的,我看了一下,这个是deepin-wine的版本,原版Wine版本是5.4,更换至wine后程序能够打开

**Comment by Chengnan049** [comment]
> 你的系统是 Archlinux吗，Archlinux上wine最新的版本是 `5.4`，wine版本过旧可能不支持

是的，图中所显示的是deepin-wine版本
