### ISSUE TITLE
gnome-settings-daemon破坏了原有的gtk主题

### ISSUE THREAD

**Issue by DarthRL** [countstarlight/deepin-wine-tim-arch#47]
非gnome桌面，原先设置了gtk主题，当启动gsd-xsettings时原有的主题就被破坏了，变回了adwaita。
 解决方法是用gsettings再设置一遍主题：
`$ gsettings set org.gnome.desktop.interface gtk-theme theme-name`
`$ gsettings set org.gnome.desktop.interface icon-theme theme-name`

**Comment by countstarlight** [comment]
最新版(`3.0.0.21315-2`)用 `xsettingsd` 替代了 `gsd-xsettings`，用[自动切换](https://github.com/countstarlight/deepin-wine-tim-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2)即可
