### ISSUE TITLE
Manjaro KDE上切换成deepin-wine之后打开直接闪退

### ISSUE THREAD

**Issue by MiraculousMoon** [countstarlight/deepin-wine-tim-arch#48]

**Comment by MiraculousMoon** [comment]
终端运行之后的报错：（后面的部分）
err:font:add_replace_font not found suitable family L"\601d\6e90\9ed1\4f53 Regular"
err:font:add_replace_font not found suitable family L"\601d\6e90\9ed1\4f53 Regular"
err:font:add_replace_font not found suitable family L"\601d\6e90\9ed1\4f53 Regular"
fixme:resource:GetGuiResources (0x3a4,0): stub
fixme:dbghelp:elf_search_auxv can't find symbol in module
err:dbghelp_msc:codeview_process_info Unknown CODEVIEW signature 0bdf3368 in module L"tssafeedit.dat"
fixme:dbghelp:elf_search_auxv can't find symbol in module
fixme:uxtheme:DrawThemeTextEx unsupported flags 0x00020053
fixme:uxtheme:DrawThemeTextEx unsupported flags 0x00090060
fixme:uxtheme:DrawThemeTextEx unsupported flags 0x000800bd
fixme:uxtheme:DrawThemeTextEx unsupported flags 0x0002004f
fixme:uxtheme:DrawThemeTextEx unsupported flags 0x00010052
fixme:uxtheme:DrawThemeTextEx unsupported flags 0x00010052
fixme:uxtheme:DrawThemeTextEx unsupported flags 0x0002004f
fixme:uxtheme:DrawThemeTextEx unsupported flags 0x00010052
fixme:uxtheme:DrawThemeTextEx unsupported flags 0x0002004f
fixme:uxtheme:DrawThemeTextEx unsupported flags 0x00010052

**Comment by countstarlight** [comment]
使用原版 `wine` 会有问题吗

**Comment by MiraculousMoon** [comment]
> 使用原版 `wine` 会有问题吗

原版不会闪退

**Comment by MiraculousMoon** [comment]
> 使用原版 `wine` 会有问题吗

但是俺想要记住密码自动登录……
