### ISSUE TITLE
run.sh 启动了一个新的 tim 而不是唤出当前 tim 窗口

### ISSUE THREAD

**Issue by amosbird** [countstarlight/deepin-wine-tim-arch#50]
请问有办法让tim 的 run.sh 表现得和  wechat 的 run.sh 一样吗？ 保证单例运行

**Comment by countstarlight** [comment]
tim在windows上也是多开的，不好实现

**Comment by amosbird** [comment]
好吧，幸运的是 qq 还是用的比较少，wechat 倒是很方便

**Comment by NotAlone777** [comment]
你要用的deepin-wine的话，直接调用/opt/deepinwine/tools/sendkeys.sh z  就能触CTRL+ALT+z这个快捷键，同理也能设置截图的快捷键

**Comment by amosbird** [comment]
@NotAlone777 感谢
