### ISSUE TITLE
输入法的位置出现在窗口外而不是光标附近，且不跟随光标

### ISSUE THREAD

**Issue by amosbird** [countstarlight/deepin-wine-tim-arch#51]
这个问题是否是wine的限制呢，有没有什么解决方案呢

**Comment by countstarlight** [comment]
这个的 `wine` 的问题，`wine` 的窗口和原生窗口不同，暂时没有解决版本

**Comment by countstarlight** [comment]
在 `deepin-wine 2.18_24-3` 和 `fcitx 4.2.9.8-1` 上，输入法窗口已经能跟随光标

**Comment by amosbird** [comment]
是的，deepin 着实给力
