### ISSUE TITLE
Manjaro 20.3 KDE 环境不能使用“yay -Sy deepin-wine-tim”命令进行安装

### ISSUE THREAD

**Issue by masonsxu** [countstarlight/deepin-wine-tim-arch#55]
在安装deepin-wine-tim时报错不能进行最后一步，不能下载tim的deb格式源文件;
报错信息：
 -> 正在下载 deepin.com.qq.office_2.0.0deepin4_i386.deb...
正在初始化下载：https://mirrors.ustc.edu.cn/deepin/pool/non-free/d/deepin.com.qq.office/deepin.com.qq.office_2.0.0deepin4_i386.deb
File size: 75742786 bytes
找到状态文件，但未有下载数据。重新开始下载。
正在打开输出文件 deepin.com.qq.office_2.0.0deepin4_i386.deb.part
正在开始下载

==> 错误： 无法下载 https://mirrors.ustc.edu.cn/deepin/pool/non-free/d/deepin.com.qq.office/deepin.com.qq.office_2.0.0deepin4_i386.deb
    正在放弃...
Error downloading sources: deepin-wine-tim
end...
不知道是不是我的网络问题，修改国内镜像源的时候也只能找到三个：
## Country : China
Server = https://mirrors.sjtug.sjtu.edu.cn/manjaro/stable/$repo/$arch

## Country : China
Server = https://mirrors.ustc.edu.cn/manjaro/stable/$repo/$arch

## Country : China
Server = https://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/$repo/$arch
不完整。
因为我也是刚刚接触manjaro,不是很熟悉，希望大佬能帮忙看一下。

**Comment by zhullyb** [comment]
可能是ustc在你那边比较慢，多试几次或者手动改一下PKGBUILD的地址吧
这不是你选的manjaro源的问题

**Comment by masonsxu** [comment]
> 可能是ustc在你那边比较慢，多试几次或者手动改一下PKGBUILD的地址吧
> 这不是你选的manjaro源的问题

我太菜了，不太会;
makepkg -s                                                                   
==> 错误： 文件 install (deepin-wine-qq.install) 不存在，或者不是一个常规文件。

**Comment by countstarlight** [comment]
@masonsxu 参考[用安装包安装](https://github.com/countstarlight/deepin-wine-tim-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)

**Comment by masonsxu** [comment]
> @masonsxu 参考[用安装包安装](https://github.com/countstarlight/deepin-wine-tim-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)

好了，安装成功了。但是总感觉可能会出问题，暂时先这样了，不过还是很感谢。
