### ISSUE TITLE
系统安装微软字体之后tim字体强制变为宋体

### ISSUE THREAD

**Issue by arxim-lab** [countstarlight/deepin-wine-tim-arch#56]
就像这样  

![22003814.png](https://i.loli.net/2020/06/22/lstNvinkC3AOP4U.png)  

按照教程在文件夹里加字体也没用
而且个人比较倾向于思源黑体字体

**Comment by arxim-lab** [comment]
![2020-06-22_00-43.png](https://i.loli.net/2020/06/22/CrmnzYVB37auqJ1.png)  

这个是系统环境

字体是直接拷贝的win10的字体文件夹，放在了/usr/share/fonts文件夹下

**Comment by countstarlight** [comment]
系统的字体优先级最高，这个在 `wine` 上暂时不能解决

**Comment by arxim-lab** [comment]
> 系统的字体优先级最高，这个在 `wine` 上暂时不能解决

那我想请教一下，既然用了系统字体为什么这个字体他不是微软雅黑呢::cry
能不能通过修改注册表的方式让他强制使用自己定义的字体或者使用正确的系统字体

**Comment by abcfy2** [comment]
如果你的容器设置的系统是XP,那么就是默认宋体，设置Win7及以上就是默认雅黑

**Comment by arxim-lab** [comment]
> 如果你的容器设置的系统是XP,那么就是默认宋体，设置Win7及以上就是默认雅黑。
> 
> 运行`WINEPREFIX=~/.deepinwine/Deepin-TIM winecfg`(使用wine时)或`WINEPREFIX=~/.deepinwine/Deepin-TIM deepin-wine winecfg`(使用deepin-wine时)打开wine设置，看看操作系统那里选择的是不是XP

好的，我等下试试，不过还是想问一下，能不能设置全部使用思源黑体

**Comment by abcfy2** [comment]
wine的字体设置比较麻烦，老实说我也不是特别懂wine的字体设置，因为它一直给我的感觉非常的迷。

不过我觉得如果你的系统没有对于windows来说优先级比较高的字体（如雅黑、宋体等等），那么wine优先会使用系统fontconfig的配置（至少给我的感觉是这样的）。比如你的系统没有雅黑、宋体，也没有对于fontconfig默认配置来说优先级非常高的文泉驿微米黑，那么wine是用的中文字体似乎就是你的系统的默认无衬线字体，如果你系统设置的就是思源黑体，那么就是思源黑体。

否则你可能需要自己去该wine的注册表。万幸的是有个比较简单的做法就是使用`winestricks`安装`fakechinese`这个包，它用的中文字体就是思源黑体，并且会帮你改注册表：

```shell
# wine
WINEPREFIX=~/.deepinwine/Deepin-TIM winetricks fakechinese

#deepin-wine
WINEPREFIX=~/.deepinwine/Deepin-TIM WINE=deepin-wine winetricks fakechinese
```

尽管这样，某些使用了一些英文字体的地方可能还是会出现方块，暂时无解，比如系统设置顶上的菜单栏，比如聊天窗口顶上的群名或者昵称等等。

如果你用的是deepin-wine，那么很多这些地方的中文都不会有方框，应该是它做了什么黑科技的设置，暂时不知道怎么做到的，对于TIM还是尽可能用deepin-wine运行吧，问题少。

总之就是wine的字体折腾真的很迷，能显示出来你就万幸吧，就别折腾了，别要求太多

**Comment by arxim-lab** [comment]
> wine的字体设置比较麻烦，老实说我也不是特别懂wine的字体设置，因为它一直给我的感觉非常的迷。
> 
> 不过我觉得如果你的系统没有对于windows来说优先级比较高的字体（如雅黑、宋体等等），那么wine优先会使用系统fontconfig的配置（至少给我的感觉是这样的）。比如你的系统没有雅黑、宋体，也没有对于fontconfig默认配置来说优先级非常高的文泉驿微米黑，那么wine是用的中文字体似乎就是你的系统的默认无衬线字体，如果你系统设置的就是思源黑体，那么就是思源黑体。
> 
> 否则你可能需要自己去该wine的注册表。万幸的是有个比较简单的做法就是使用`winestricks`安装`fakechinese`这个包，它用的中文字体就是思源黑体，并且会帮你改注册表：
> 
> ```shell
> # wine
> WINEPREFIX=~/.deepinwine/Deepin-TIM winetricks fakechinese
> 
> #deepin-wine
> WINEPREFIX=~/.deepinwine/Deepin-TIM WINE=deepin-wine winetricks fakechinese
> ```
> 
> 尽管这样，某些使用了一些英文字体的地方可能还是会出现方块，暂时无解，比如系统设置顶上的菜单栏，比如聊天窗口顶上的群名或者昵称等等。
> 
> 如果你用的是deepin-wine，那么很多这些地方的中文都不会有方框，应该是它做了什么黑科技的设置，暂时不知道怎么做到的，对于TIM还是尽可能用deepin-wine运行吧，问题少。
> 
> 总之就是wine的字体折腾真的很迷，能显示出来你就万幸吧，就别折腾了，别要求太多

我的deepin-wine安装不了fakechinese，wine版本太低

**Comment by abcfy2** [comment]
> > wine的字体设置比较麻烦，老实说我也不是特别懂wine的字体设置，因为它一直给我的感觉非常的迷。
> > 不过我觉得如果你的系统没有对于windows来说优先级比较高的字体（如雅黑、宋体等等），那么wine优先会使用系统fontconfig的配置（至少给我的感觉是这样的）。比如你的系统没有雅黑、宋体，也没有对于fontconfig默认配置来说优先级非常高的文泉驿微米黑，那么wine是用的中文字体似乎就是你的系统的默认无衬线字体，如果你系统设置的就是思源黑体，那么就是思源黑体。
> > 否则你可能需要自己去该wine的注册表。万幸的是有个比较简单的做法就是使用`winestricks`安装`fakechinese`这个包，它用的中文字体就是思源黑体，并且会帮你改注册表：
> > 
> >       
> >         
> >       
> >     ```shell
> > # wine
> > WINEPREFIX=~/.deepinwine/Deepin-TIM winetricks fakechinese
> > 
> > #deepin-wine
> > WINEPREFIX=~/.deepinwine/Deepin-TIM WINE=deepin-wine winetricks fakechinese
> > ```
> > 
> > 
> > 尽管这样，某些使用了一些英文字体的地方可能还是会出现方块，暂时无解，比如系统设置顶上的菜单栏，比如聊天窗口顶上的群名或者昵称等等。
> > 如果你用的是deepin-wine，那么很多这些地方的中文都不会有方框，应该是它做了什么黑科技的设置，暂时不知道怎么做到的，对于TIM还是尽可能用deepin-wine运行吧，问题少。
> > 总之就是wine的字体折腾真的很迷，能显示出来你就万幸吧，就别折腾了，别要求太多
> 
> 我的deepin-wine安装不了fakechinese，wine版本太低

我试过是可以的，那个wine版本太低只是警告，实际fackechinese还是可以装上的。不过我这边用deepin-wine运行TIM的话，中文字体是没问题的，所以就没必要折腾了。之前我记得我试过是可以的，会有个警告说winetricks最低支持4.0,当前2.18版本运行可能有问题，但是实际可以运行下去

**Comment by qiujiangkun** [comment]
经过测试，留下STZHONGS.TTF和STXIHEI.TTF会有比较好的效果. 留下simsun.tcc会导致TIM字体发虚
