### ISSUE TITLE
导入来自Windows的所有字体后导致TIm启动缓慢，微信没有问题

### ISSUE THREAD

**Issue by zhullyb** [countstarlight/deepin-wine-tim-arch#58]
我这边Archlinux下导入了所有的win10字体以后导致了TIM启动缓慢，风扇狂转，大概要二三十秒才能出现登录界面，一旦移除win10的字体就恢复到以前的正常启动速度（六七秒）
尝试了wine和deepinwine都有这个问题。
我导入win10的步骤是直接复制C盘字体文件夹下的所有字体到/usr/share/fonts/win(自己建的文件夹)，然后执行sudo fc-cache -fv，也不知道我的导入步骤是不是有问题。系统环境是Archlinux+KDE
（因为需要在Linux下操作office，确实需要这些字体，网页版不够用）
![图片](https://user-images.githubusercontent.com/43305366/85834948-d436f300-b7c6-11ea-86dd-34f44bbe075b.png)

**Comment by abcfy2** [comment]
deepin-wine似乎没有这个问题，应该是做了什么黑科技的优化。字体太多太大wine就是拖不动。直接用deepin-wine吧，那个默认字体配置就是OK的，也不会卡。如果自己用wine,那个字体配置可能会搞得你怀疑人生，各种方块字体，各种改注册表换字体

**Comment by zhullyb** [comment]
> deepin-wine似乎没有这个问题，应该是做了什么黑科技的优化。字体太多太大wine就是拖不动。直接用deepin-wine吧，那个默认字体配置就是OK的，也不会卡。如果自己用wine,那个字体配置可能会搞得你怀疑人生，各种方块字体，各种改注册表换字体

抱歉，用的就是deepin-wine

**Comment by SamLukeYes** [comment]
> deepin-wine似乎没有这个问题，应该是做了什么黑科技的优化。字体太多太大wine就是拖不动。直接用deepin-wine吧，那个默认字体配置就是OK的，也不会卡。如果自己用wine,那个字体配置可能会搞得你怀疑人生，各种方块字体，各种改注册表换字体

最近更新了deepin-wine以后，TIM的启动速度就和wine下一样慢了

**Comment by abcfy2** [comment]
我发现出问题的是宋体(simsun)，把这个字体删掉再启动就丝滑般流畅了

**Comment by zhullyb** [comment]
> 我发现出问题的是宋体(simsun)，把这个字体删掉再启动就丝滑般流畅了

原来是这样，那谢谢提醒了

**Comment by 1900011604** [comment]
但是删除宋体后文字就显示不出来了，而且还会很卡，输入不了帐号和密码，也点不了退出

**Comment by masonsxu** [comment]
> 我这边Archlinux下导入了所有的win10字体以后导致了TIM启动缓慢，风扇狂转，大概要二三十秒才能出现登录界面，一旦移除win10的字体就恢复到以前的正常启动速度（六七秒）
> 尝试了wine和deepinwine都有这个问题。
> 我导入win10的步骤是直接复制C盘字体文件夹下的所有字体到/usr/share/fonts/win(自己建的文件夹)，然后执行sudo fc-cache -fv，也不知道我的导入步骤是不是有问题。系统环境是Archlinux+KDE
> （因为需要在Linux下操作office，确实需要这些字体，网页版不够用）
> ![图片](https://user-images.githubusercontent.com/43305366/85834948-d436f300-b7c6-11ea-86dd-34f44bbe075b.png)

尝试将字体放置到 /home/用户目录/.deepinwine/Deepin-TIM/drive_c/windows/Fonts 下，能够稍微提升一些流畅度

**Comment by qiujiangkun** [comment]
经过测试，留下STZHONGS.TTF和STXIHEI.TTF会有比较好的效果. 留下simsun.tcc会导致TIM字体发虚

**Comment by zhullyb** [comment]
最新版本已经没有启动缓慢容易卡死的问题，至于导入simsun的显示问题在我这一篇博客里也已经详细描述了解决方案，是时候关issue了
https://blog.zhullyb.top/2021/04/27/hide-simsun-from-deepin-wine-tim/
