### ISSUE TITLE
KDE 无法输入表情，右键功能无法使用

### ISSUE THREAD

**Issue by BlindingDark** [countstarlight/deepin-wine-tim-arch#60]
疑似是更新了 KDE 导致的，这个现象和 XFCE 中的很像，这里是 XFCE 的解决办法，可惜我在 KDE 里没有找到对应操作。
https://wiki.archlinux.org/index.php/Tencent_QQ_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#xfce4%EF%BC%88xfwm4%EF%BC%89%E4%B8%8B%E6%97%A0%E6%B3%95%E8%BE%93%E5%85%A5%E8%A1%A8%E6%83%85

尝试把焦点防窃取设置为无，没有用。

---

操作系统： Manjaro Linux
KDE Plasma 版本： 5.19.3
KDE 框架版本： 5.72.0
Qt 版本： 5.15.0
内核版本： 5.7.9-1-MANJARO

**Comment by countstarlight** [comment]
archlinux + kde没有问题，现在问题还在吗？

**Comment by BlindingDark** [comment]
最近几个版本更新之后有所缓解，可能要点击多几次才能成功，不过也算是可以用了，就是要多点几次。
