### ISSUE TITLE
无法显示头像

### ISSUE THREAD

**Issue by NIL-zhuang** [countstarlight/deepin-wine-tim-arch#64]
新版本3.1.0.21789-1的tim安装deepin-wine后无法显示头像

**Comment by countstarlight** [comment]
切换到 `deepin-wine` 应该不存在这个问题，可以参考：https://github.com/countstarlight/deepin-wine-tim-arch/issues/42

**Comment by NIL-zhuang** [comment]
> 切换到 `deepin-wine` 应该不存在这个问题，可以参考：#42

切换到deepin-wine后重启可以解决，但是在PC不重启的情况下，退出tim再重新登录可以复现问题，头像都是原始头像，表情包无法加载

**Comment by xz-dev** [comment]
> > 切换到 `deepin-wine` 应该不存在这个问题，可以参考：#42
> 
> 切换到deepin-wine后重启可以解决，但是在PC不重启的情况下，退出tim再重新登录可以复现问题，头像都是原始头像，表情包无法加载

因为 TIM 不会主动退出它自己
在每次退出 TIM 后，请执行 `killall TIM.exe`

**Comment by xz-dev** [comment]
建议检测 TIM 是否退出（即取消了它的系统托盘），而自动 kill 进程 @countstarlight
