### ISSUE TITLE
多出一个Windows窗口

### ISSUE THREAD

**Issue by 1900011604** [countstarlight/deepin-wine-tim-arch#67]
![图片](https://user-images.githubusercontent.com/65082432/91313728-4a1c0280-e7e8-11ea-8290-a7eaaa560002.png)

左上角这个窗口无法消除，每次登录都会有

**Comment by lt-123** [comment]
> ![图片](https://user-images.githubusercontent.com/65082432/91313728-4a1c0280-e7e8-11ea-8290-a7eaaa560002.png)
> 
> 左上角这个窗口无法消除，每次登录都会有

这个是托盘，关掉它，最小化程序，就没办法恢复了。 建议安装个gnome插件 topicon plus ，可完美解决你的问题

**Comment by 1900011604** [comment]
谢谢，解决得很好！
