### ISSUE TITLE
点出窗口后，窗口不是在最前？

### ISSUE THREAD

**Issue by wastee** [countstarlight/deepin-wine-tim-arch#7]
Arch Linux
Gnome桌面

问题：每次在托盘里点开tim，或者用xdotools调出tim，tim并没有在最前的窗口，除非本来桌面没有打开的窗口。

**Comment by countstarlight** [comment]
暂时没找到解决办法，我去相关论坛上提问一波

**Comment by countstarlight** [comment]
打开winecfg:
```shell
env WINEPREFIX="$HOME/.deepinwine/Deepin-TIM" winecfg
```
切换到`Graphics`选项卡，取消勾选`Allow the window manager to control the windows`试试
原问题：https://forum.winehq.org/viewtopic.php?f=2&t=30164&e=0

**Comment by wastee** [comment]
谢谢你的回复，问题已解决。
