### ISSUE TITLE
安装后无法启动

### ISSUE THREAD

**Issue by soarteam** [countstarlight/deepin-wine-tim-arch#72]
[backtrace.txt](https://github.com/countstarlight/deepin-wine-tim-arch/files/5195567/backtrace.txt)

**Comment by soarteam** [comment]
$ /opt/deepinwine/apps/Deepin-TIM/run.sh
$ 0648:fixme:ntdll:EtwEventRegister ({dc55d4d9-138d-441a-80cb-77aec617e2db}, 00401445, 00407528, 00407A38) stub.
0648:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
wine: Unhandled page fault on execute access to DEADDEAD at address DEADDEAD (thread 0648), starting debugger...

**Comment by countstarlight** [comment]
使用[自动切换](https://github.com/countstarlight/deepin-wine-tim-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E6%8E%A8%E8%8D%90)切换到 `deepin-wine`：
```bash
/opt/deepinwine/apps/Deepin-TIM/run.sh -d
```
