### ISSUE TITLE
后续无法打开

### ISSUE THREAD

**Issue by EarthChen** [countstarlight/deepin-wine-tim-arch#8]
只能安装后第一次打开，后续就无法显示tim界面

**Comment by countstarlight** [comment]
是什么桌面环境？

**Comment by EarthChen** [comment]
manjaro

**Comment by countstarlight** [comment]
桌面是Kde，还是Gnome？运行一下:
```shell
 /opt/deepinwine/apps/Deepin-TIM/run.sh 
```
看看有什么输出

**Comment by EarthChen** [comment]
xfce

**Comment by EarthChen** [comment]
@countstarlight 运行完输出
env: "deepin-wine": 没有那个文件或目录
env: "deepin-wine": 没有那个文件或目录

**Comment by countstarlight** [comment]
检查`WINE_CMD` 在文件 `～/.deepinwine/Deepin-TIM/drive_c/deepin/EnvInit.sh` 如果是 `deepin-wine`, 改为`wine`:
```diff
- WINE_CMD="deepin-wine"
+ WINE_CMD="wine"

```

**Comment by countstarlight** [comment]
已经修复该问题 https://github.com/countstarlight/deepin-wine-tim-arch/commit/498526c5c72089e5066b461638f9d5eb86325e64
