### ISSUE TITLE
4K分辨率窗口过小，并且拖动打开的图片会乱飞

### ISSUE THREAD

**Issue by qiujiangkun** [countstarlight/deepin-wine-tim-arch#80]
安装aur里的deepin-wine-tim，Manjaro系统，xfce4桌面
4K分辨率窗口过小，并且拖动打开的图片会乱飞
有办法解决吗？

**Comment by countstarlight** [comment]
参照 [高分辨率屏幕支持](https://github.com/countstarlight/deepin-wine-tim-arch#%E9%AB%98%E5%88%86%E8%BE%A8%E7%8E%87%E5%B1%8F%E5%B9%95%E6%94%AF%E6%8C%81)，与 https://github.com/countstarlight/deepin-wine-tim-arch/issues/62 ，https://github.com/countstarlight/deepin-wine-tim-arch/issues/1 重复

**Comment by qiujiangkun** [comment]
我已经参考 高分辨率屏幕支持 解决了窗口过小的问题，但图片乱飞的问题还没有解决。

**Comment by qiujiangkun** [comment]
![BugReport](https://user-images.githubusercontent.com/33482468/95857168-c9ac6380-0d8d-11eb-8c87-6f9cbbc6312b.gif)
