### ISSUE TITLE
软件Deb包已被上游清除

### ISSUE THREAD

**Issue by RigoLigoRLC** [countstarlight/deepin-wine-tim-arch#84]
https://www.deepin.org/zh/2020/11/19/statements/
Deepin-Wine应用程序已经从主仓库彻底清除

**Comment by Core00077** [comment]
搜了一下，deepin-wine-tim相关的应用主要是迁移。deb包在新的[仓库](https://packages.deepin.com/deepin/pool/non-free/d/deepin.com.qq.office/deepin.com.qq.office_2.0.0deepin4_i386.deb)还是可以使用的，deepin-wine也在

**Comment by countstarlight** [comment]
已更新：https://github.com/countstarlight/deepin-wine-tim-arch/commit/947dcd12d18aebde90c7b7985bbff85b950f24d0 ，基于deepin打包的使用 deepin-wine5 的QQ容器，QQ 环境修改为 TIM
