### ISSUE TITLE
有考虑迁移到deepin-wine5吗？

### ISSUE THREAD

**Issue by NotAlone777** [countstarlight/deepin-wine-tim-arch#85]
deepin-wine5的微信使用体验挺好的，不知道这个迁移到deepin-wine5体验会不会上升。

**Comment by countstarlight** [comment]
deepin 还没有打包使用 `deepin-wine5` 的TIM，暂时不会迁移；QQ的打包已经有了，后续应该会把QQ迁移到 `deepin-wine5`

**Comment by NotAlone777** [comment]
> deepin 还没有打包使用 `deepin-wine5` 的TIM，暂时不会迁移；QQ的打包已经有了，后续应该会把QQ迁移到 `deepin-wine5`

好的，辛苦了

**Comment by I-Info** [comment]
手动改一下run.sh脚本，把所有deepin-wine改成deepin-wine5（前提是已安装了deepin-wine5）
就可以用deepin-wine5启动了。
实测可用，目前使用没有出现任何问题。

**Comment by I-Info** [comment]
脚本改完后可能需要用`run.sh -d` 更新一下。

**Comment by countstarlight** [comment]
已更新：https://github.com/countstarlight/deepin-wine-tim-arch/commit/947dcd12d18aebde90c7b7985bbff85b950f24d0 ，基于deepin打包的使用 deepin-wine5 的QQ容器，QQ 环境修改为 TIM
