### ISSUE TITLE
窗口管理器用户在安装TIM安装包时，直接运行/opt/deepinwine/apps/Deepin-TIM/run.sh吗？

### ISSUE THREAD

**Issue by Onetopabove** [countstarlight/deepin-wine-tim-arch#86]
1.  我是直接这么做的，安装完后直接就有`~/.deepin-wine`文件夹了。接着，我无法直接用wine运行（报错信息说wine的版本之类不对等等）,只好用

> 自动切换(推荐)

然后再用deepin-wine打开，成功运行。所以这里是否存在一个问题，即非桌面环境用户（没有

> 应用菜单中创建的 TIM 快捷方式

）需要用其他命令来安装TIM使得直接用wine就能使用安装后的TIM？
 

2.  一开始由于新接触wine所以，在安装完后不知道怎么启动，希望作者添加一些命令行命令到README.md。不过后来知道了，我用的命令是`WINEPREFIX=~/.deepinwine/Deepin-TIM 
   deepin-wine start 'C:\Program Files\Tencent\TIM\Bin\TIM.exe'`。这个命令和在安装完TIM安装包后再次运行/opt/deepinwine/apps/Deepin-TIM/run.sh都可以正常运行TIM。这二者有何区别？

3.  还有，对于

> 切换到`deepin-wine`

意味着什么不甚清楚。希望作者能添加一些解释或说明到README.md中。

4. 最后一个建议，希望能在run.sh中添加一些注释。

**Comment by countstarlight** [comment]
1. 点击 应用菜单中创建的 TIM 快捷方式等同于运行：
```bash
/opt/deepinwine/apps/Deepin-TIM/run.sh
```
根据 [兼容性记录](https://github.com/countstarlight/deepin-wine-tim-arch#%E5%85%BC%E5%AE%B9%E6%80%A7%E8%AE%B0%E5%BD%95)，`wine` 不支持 `3.2.0.21856` 版本 TIM，所以用 `wine` 不能启动，如果要用 `wine` 可以降级到旧版本的 TIM

2.  与 `WINEPREFIX=~/.deepinwine/Deepin-TIM deepin-wine start 'C:\Program Files\Tencent\TIM\Bin\TIM.exe'` 类似的命令已经包含在 上述的 `run.sh` 中，`run.sh` 的作用是：
* TIM 未安装时加载安装程序
* TIM 已安装时启动已安装的TIM
* 切换到 `deepin-wine` 后，用`deepin-wine` 代替 `wine` 启动程序
3. 切换到 `deepin-wine` 是指用 `deepin-wine` 代替 `deepin-wine-tim` 默认使用的 `wine`，来解决上述 `3.2.0.21856` 不能启动的问题

**Comment by Onetopabove** [comment]
不好意思，我之前没有给出我用的TIM版本。我参考过[兼容性记录](https://github.com/countstarlight/deepin-wine-tim-arch#%E5%85%BC%E5%AE%B9%E6%80%A7%E8%AE%B0%E5%BD%95)后选定了以下版本。
![2020-11-27_14-41](https://user-images.githubusercontent.com/38457754/100419084-c8759280-30be-11eb-969d-68bf6c7007a7.png)
目前我已成功安装并可以正常使用TIM，只是有一些小问题。
我总结下我在安装和使用软件过程中的一些理解，如有错误，还请纠正：

1. 根据[兼容性记录](https://github.com/countstarlight/deepin-wine-tim-arch#%E5%85%BC%E5%AE%B9%E6%80%A7%E8%AE%B0%E5%BD%95)选定一个TIM版本
2. 根据所选版本，从三种方式任选一种[安装](https://github.com/countstarlight/deepin-wine-tim-arch#%E5%AE%89%E8%A3%85)。得到安装后的安装目录`/opt/deepinwine`，其中
![2020-11-27_14-57](https://user-images.githubusercontent.com/38457754/100420265-17bcc280-30c1-11eb-8c17-c8fb67bf02d7.png)是win平台上的安装包。
**这一步安装的是wine和deepin-wine软件。**
3. 使用应用菜单中创建的 TIM 快捷方式（桌面环境用户）或`/opt/deepinwine/apps/Deepin-TIM/run.sh`脚本（不带参数）来安装。**这一步才是安装TIM。**
容器的安装目录为`～/.deepinwine/Deepin-TIM`
4. 安装完后即可通过桌面图标或`/opt/deepinwine/apps/Deepin-TIM/run.sh`（依旧不带参数）来使用TIM（用wine启动TIM到这就可以正常使用，想用deepin-wine的继续）
5. 切换到`deepin-wine`，使用`/opt/deepinwine/apps/Deepin-TIM/run.sh -d`（**带参数`-d`**）。
**切换会删掉原来的容器，重新安装TIM。**
6. 不管使用wine还是deepin-wine，容器名称都是`～/.deepinwine/Deepin-TIM`

**Comment by countstarlight** [comment]
> 不好意思，我之前没有给出我用的TIM版本。我参考过[兼容性记录](https://github.com/countstarlight/deepin-wine-tim-arch#%E5%85%BC%E5%AE%B9%E6%80%A7%E8%AE%B0%E5%BD%95)后选定了以下版本。
> ![2020-11-27_14-41](https://user-images.githubusercontent.com/38457754/100419084-c8759280-30be-11eb-969d-68bf6c7007a7.png)
> 目前我已成功安装并可以正常使用TIM，只是有一些小问题。
> 我总结下我在安装和使用软件过程中的一些理解，如有错误，还请纠正：
> 
> 1. 根据[兼容性记录](https://github.com/countstarlight/deepin-wine-tim-arch#%E5%85%BC%E5%AE%B9%E6%80%A7%E8%AE%B0%E5%BD%95)选定一个TIM版本
> 2. 根据所选版本，从三种方式任选一种[安装](https://github.com/countstarlight/deepin-wine-tim-arch#%E5%AE%89%E8%A3%85)。得到安装后的安装目录`/opt/deepinwine`，其中
>    ![2020-11-27_14-57](https://user-images.githubusercontent.com/38457754/100420265-17bcc280-30c1-11eb-8c17-c8fb67bf02d7.png)是win平台上的安装包。
>    **这一步安装的是wine和deepin-wine软件。**
> 3. 使用应用菜单中创建的 TIM 快捷方式（桌面环境用户）或`/opt/deepinwine/apps/Deepin-TIM/run.sh`脚本（不带参数）来安装。**这一步才是安装TIM。**
>    容器的安装目录为`～/.deepinwine/Deepin-TIM`
> 4. 安装完后即可通过桌面图标或`/opt/deepinwine/apps/Deepin-TIM/run.sh`（依旧不带参数）来使用TIM（用wine启动TIM到这就可以正常使用，想用deepin-wine的继续）
> 5. 切换到`deepin-wine`，使用`/opt/deepinwine/apps/Deepin-TIM/run.sh -d`（**带参数`-d`**）。
>    **切换会删掉原来的容器，重新安装TIM。**
> 6. 不管使用wine还是deepin-wine，容器名称都是`～/.deepinwine/Deepin-TIM`

对，你的理解很清晰，`run.sh` 的参数 `-d` 只在切换时使用，用户目录下的容器路径不变
