### ISSUE TITLE
deepin-wine 已经被移除

### ISSUE THREAD

**Issue by kingcanfish** [countstarlight/deepin-wine-tim-arch#87]
deepin-wine 现在被移除了,只有 deepin-wine5 和deepin-wine32了
![image](https://user-images.githubusercontent.com/43931057/102004578-e98be380-3d4c-11eb-97df-ab4180e77a50.png)

**Comment by SamLukeYes** [comment]
可以暂时先用着 com.qq.tim.spark 或者 deepin.com.qq.im.light

**Comment by countstarlight** [comment]
已更新：https://github.com/countstarlight/deepin-wine-tim-arch/commit/947dcd12d18aebde90c7b7985bbff85b950f24d0 ，基于deepin打包的使用 deepin-wine5 的QQ容器，QQ 环境修改为 TIM
