### ISSUE TITLE
强迫症请求改改安装目录

### ISSUE THREAD

**Issue by eonun** [countstarlight/deepin-wine-tim-arch#88]
强迫症请求改改安装目录，像微信和QQ一样放到`/opt/apps/`下
如将`/opt/deepinwine/apps/Deepin-TIM`改到`/opt/apps/com.qq.office.deepin/`什么的

**Comment by TTTPOB** [comment]
#87 
其实是因为deepin-wine的版本问题所以路径不一样，看上去你也可以自己改一个用deepin-wine5并且符合强迫症习惯路径的版本

**Comment by countstarlight** [comment]
`deepin-wine-tim v3.3.0.22020-1` 已经修改了安装路径
