### ISSUE TITLE
找不到run_v3.sh

### ISSUE THREAD

**Issue by BlueQuantumx** [countstarlight/deepin-wine-tim-arch#89]
更新完3.3后启动失败
报错信息找不到了，因为我自己已经修好了
它在找用户主目录下的./deepinwine/deepin-wine-helper/run_v3.sh但是没有，我找到了/opt/deepinwine/tools/run_v3.sh
于是我把那个tools链接过去了，就好了。
我的deepinwine-helper是在arch源里安装的，不知道和这个有关系没有

**Comment by countstarlight** [comment]
`deepin-wine-tim` 自带 `deepin-wine-helper`，每次启动或切换时会检测 `$HOME/.deepinwine/deepin-wine-helper` ，不存在就会解压缩自带的 `deepin-wine-helper` 到该路径，应该不会出现该问题。可以手动删除 `$HOME/.deepinwine/deepin-wine-helper`，再运行：
```bash
/opt/apps/com.qq.office.deepin/files/run.sh
```
看能否复现该问题

**Comment by BlueQuantumx** [comment]
emmm，能不能把
`deepin-wine-helper`放到opt下面，这样看起来更正式，位置更固定（或者直接用源里那个单独的包？
因为我用tools里面的那个sendkeys.sh做了一个快捷键，换位置就失效了。

**Comment by countstarlight** [comment]
目前 deepin 打包的使用 `deepin-wine5` 的安装包都自带 `deepin-wine-helper`，其安装位置都是 `$HOME/.deepinwine/deepin-wine-helper`，启动脚本也都调用的是这个自带的  `deepin-wine-helper`；移植到Archlinux时最大限度的保留了这些逻辑，不知道这个自带的 `deepin-wine-helper` 之后会不会和源里的那个单独的包有差别

**Comment by BlueQuantumx** [comment]
行吧
