### ISSUE TITLE
经常崩溃

### ISSUE THREAD

**Issue by GreenHatHG** [countstarlight/deepin-wine-tim-arch#9]
[CDVetx.png](https://s1.ax1x.com/2018/05/13/CDVetx.png)
[![CDVetx.th.png](https://s1.ax1x.com/2018/05/13/CDVetx.th.png)](https://imgchr.com/i/CDVetx)
如上图，我从aur安装后第一次打开就这样，然后后面几次打开几乎都是崩溃，不知道为什么，麻烦开发者看下
OS: Manjaro 17.1.10 Hakoila
Kernel: x86_64 Linux 4.14.39-1-MANJARO

**Comment by countstarlight** [comment]
我这边没有办法复现这个问题，或者在终端中运行:
```shell
/opt/deepinwine/apps/Deepin-TIM/run.sh 
```
看看有什么输出

**Comment by countstarlight** [comment]
参照 [切换到 `deepin-wine`](https://github.com/countstarlight/deepin-wine-tim-arch#%E5%88%87%E6%8D%A2%E5%88%B0-deepin-wine)
