### ISSUE TITLE
TIM安装完成后提示重新下载

### ISSUE THREAD

**Issue by AlvinZhu** [countstarlight/deepin-wine-tim-arch#90]
ArchLinux用户，上一个版本，配合deepin-wine使用正常。
升级到版本：deepin-wine-tim 3.3.0.22020-1，并且安装了deepin-wine5
按照文档：
```
rm $HOME/.deepinwine/Deepin-TIM/deepin
/opt/apps/com.qq.office.deepin/files/run.sh -d
```
启动TIM，首先是安装程序，正常。
安装完成后运行，TIM弹窗（传图麻烦，我就大概示意一下）：
```
提示                              X
(红色叹号)
（中间应该是有一段文字，有滚动条
无法显示，可能是wine的问题）
               重新下载       取消
```
单击`重新下载`就会用浏览器打开TIM下载页面。`取消`就退出，无法使用。
也试过换回`wine`，同样的问题，无法使用。

**Comment by countstarlight** [comment]
参照 [README](https://github.com/countstarlight/deepin-wine-tim-arch/blob/master/README.md)，新版TIM和QQ一样，前几次运行时可能会提示 "qq安全组件异常，需要重新下载"，等一会再运行或重启一下系统

**Comment by AlvinZhu** [comment]
多试了几次，确实是这样。谢谢。
