### ISSUE TITLE
通过AUR安装，deb包下载不下来 404

### ISSUE THREAD

**Issue by LonelySinging** [countstarlight/deepin-wine-tim-arch#95]
curl: (22) The requested URL returned error: 404
==> 错误： 无法下载 https://community-store-packages.deepin.com/appstore/pool/appstore/c/com.qq.im.deepin/com.qq.im.deepin_9.3.2deepin14_i386.deb
    正在放弃...

这个url软件仓库是不是调整目录结构了呢？

**Comment by countstarlight** [comment]
已更新：https://github.com/countstarlight/deepin-wine-tim-arch/commit/473622062fe7e499234a6eff47a591bc9f9da2f2
