### ISSUE TITLE
deepin-wine5中文字体异常

### ISSUE THREAD

**Issue by SituChengxiang** [countstarlight/deepin-wine-tim-arch#97]
Emmm，我用的是下载Release的本店包，并且安装过程中无明显异常，但是首次启动（Deepin-wine5启动）后中文字体似乎加载不出来，我需不需要尝试完全重新安装deepin-wine组件呢？
![image](https://user-images.githubusercontent.com/52872757/108016651-01822b00-704e-11eb-87e2-f32e5a5c5f37.png)

**Comment by countstarlight** [comment]
由于Travis CI构建出错，Release里没有最新的安装包，可以[从AUR安装](https://github.com/countstarlight/deepin-wine-tim-arch#%E4%BB%8Eaur%E5%AE%89%E8%A3%85)最新的版本

如图提示参照 [issue#90](https://github.com/countstarlight/deepin-wine-tim-arch/issues/90)，即 安装最新版后，运行一次切换命令：
```bash
/opt/apps/com.qq.office.deepin/files/run.sh -d
```
再重启一下系统，试试看

**Comment by qiujiangkun** [comment]
操作后依旧不能使用

**Comment by SituChengxiang** [comment]
感谢回复：
我已经重新安装了最新版，发现有时候更新字体需要重新启动操作系统，但有时候字体无法正常切换（似乎是deepin-wine5的设置重启后一并被重置了？），目前没有太大的问题了，谢谢

**Comment by SituChengxiang** [comment]
不好意思我又来了，切换的时候我仔细看了一下终端，发现几个错误（我的用户名为bart）：
1. ERROR: Can not open output file : 没有那个文件或目录 : /home/bart/.deepinwine/Deepin-TIM/winx/extensions.so
2. mv: 无法将'/home/bart/.deepinwine/Deepin-TIM/drive_c/users/@current_user@' 移动至'/home/bart/.deepinwine/Deepin-TIM/drive_c/users/bart/@current_user@': 目录非空
3. 还有就是这个需不需要python2依赖呢？我在终端內输出的信息看到了python2
</p>
<img src="https://pic.baixiongz.com/uploads/2021/02/20/fb1c2584ab85f.png" alt="image.png" title="image.png" />
</p>
辛苦了

**Comment by SituChengxiang** [comment]
感谢@zhullyb 的方案（https://blog.zhullyb.top/2021/04/27/hide-simsun-from-deepin-wine-tim/），manjaro xfce下已经没问题了
